- menu_name: "维护"

- name: "联系我"
  url: "/contact/"
  title: "Contact"

- name: "RSS订阅"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom订阅"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "sitemap"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
